#!/bin/bash

# setup.sh — Interactive setup script for dev-kit.
#
# Bootstraps a new project with standardized workflows, hooks, linting configs,
# and GitHub automation from the dev-kit template library.
#
# Run this script from inside your target project directory:
#   bash /path/to/dev-kit/scripts/setup.sh
#
# What it does:
#   1. Prompts for project details (framework, prefix, repo, etc.)
#   2. Generates .dev-kit.yml in the target project
#   3. Copies common templates (hooks, commitlint, workflows, issue templates, etc.)
#   4. Copies framework-specific templates (CI workflow, .gitignore, linting config)
#   5. Replaces placeholder tokens in copied files with actual project values
#   6. Validates all file names are kebab-case
#
# Prerequisites:
#   - Git initialized in the target project
#   - GitHub CLI (gh) installed and authenticated (for issue/PR automation)

set -e

# ─── Color output helpers ───────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
BOLD='\033[1m'
NC='\033[0m' # No Color

print_header() {
  echo ""
  echo -e "${BOLD}${BLUE}═══════════════════════════════════════════════════${NC}"
  echo -e "${BOLD}${BLUE}  dev-kit — Project Setup${NC}"
  echo -e "${BOLD}${BLUE}═══════════════════════════════════════════════════${NC}"
  echo ""
}

print_step() {
  echo -e "${YELLOW}[$1/$TOTAL_STEPS]${NC} $2"
}

print_success() {
  echo -e "  ${GREEN}✓${NC} $1"
}

print_warning() {
  echo -e "  ${YELLOW}!${NC} $1"
}

print_error() {
  echo -e "  ${RED}✗${NC} $1"
}

# ─── Resolve dev-kit template directory ──────────────────────────────────────────
# The templates directory is relative to this script's location
# DEV_KIT_DIR can be set by the CLI (npx) or derived from script path
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
DEV_KIT_DIR="${DEV_KIT_DIR:-$(dirname "$SCRIPT_DIR")}"
TEMPLATES_DIR="$DEV_KIT_DIR/templates"
TARGET_DIR="$(pwd)"

TOTAL_STEPS=6

# ─── Validate environment ───────────────────────────────────────────────────────
if [ ! -d "$TEMPLATES_DIR/common" ]; then
  echo -e "${RED}ERROR: Could not find dev-kit templates at $TEMPLATES_DIR${NC}"
  echo "Make sure you're running this script from the dev-kit repo."
  exit 1
fi

if [ ! -d "$TARGET_DIR/.git" ]; then
  echo -e "${RED}ERROR: Current directory is not a git repository.${NC}"
  echo "Initialize git first: git init"
  exit 1
fi

print_header

echo -e "Target project: ${BOLD}$TARGET_DIR${NC}"
echo ""

# ─── Step 1: Gather project details ─────────────────────────────────────────────
print_step 1 "Project configuration"
echo ""

# Framework selection
echo -e "  ${BOLD}Select framework:${NC}"
echo "    1) nextjs"
echo "    2) react"
echo "    3) react-native"
echo "    4) vue"
echo "    5) flutter"
echo ""
read -rp "  Enter number (1-5): " framework_choice

case $framework_choice in
  1) FRAMEWORK="nextjs" ;;
  2) FRAMEWORK="react" ;;
  3) FRAMEWORK="react-native" ;;
  4) FRAMEWORK="vue" ;;
  5) FRAMEWORK="flutter" ;;
  *)
    print_error "Invalid choice. Exiting."
    exit 1
    ;;
esac
print_success "Framework: $FRAMEWORK"

# Project prefix
echo ""
read -rp "  Project prefix (e.g., ATLAS, TEMPO): " PROJECT_PREFIX
PROJECT_PREFIX=$(echo "$PROJECT_PREFIX" | tr '[:lower:]' '[:upper:]')
if [ -z "$PROJECT_PREFIX" ]; then
  print_error "Project prefix is required. Exiting."
  exit 1
fi
print_success "Prefix: $PROJECT_PREFIX"

# GitHub repo
read -rp "  GitHub repo (e.g., ninanathalie/atlas): " GITHUB_REPO
if [ -z "$GITHUB_REPO" ]; then
  print_error "GitHub repo is required. Exiting."
  exit 1
fi
print_success "Repo: $GITHUB_REPO"

# Project board number
read -rp "  GitHub Project board number: " PROJECT_NUMBER
if [ -z "$PROJECT_NUMBER" ]; then
  print_error "Project board number is required. Exiting."
  exit 1
fi
print_success "Project board: #$PROJECT_NUMBER"

# Assignee
read -rp "  GitHub assignee username: " ASSIGNEE
if [ -z "$ASSIGNEE" ]; then
  print_error "Assignee is required. Exiting."
  exit 1
fi
print_success "Assignee: $ASSIGNEE"

# Branch names
read -rp "  Main branch name (default: main): " MAIN_BRANCH
MAIN_BRANCH="${MAIN_BRANCH:-main}"
read -rp "  Development branch name (default: develop): " DEV_BRANCH
DEV_BRANCH="${DEV_BRANCH:-develop}"
print_success "Branches: $MAIN_BRANCH / $DEV_BRANCH"

echo ""

# ─── Step 2: Generate .dev-kit.yml ───────────────────────────────────────────────
print_step 2 "Generating .dev-kit.yml"

cat > "$TARGET_DIR/.dev-kit.yml" <<EOF
# dev-kit project configuration
# Generated by dev-kit setup script

project-prefix: $PROJECT_PREFIX
github-repo: $GITHUB_REPO
github-project-number: $PROJECT_NUMBER
assignee: $ASSIGNEE
framework: $FRAMEWORK
branches:
  main: $MAIN_BRANCH
  development: $DEV_BRANCH
EOF

print_success "Created .dev-kit.yml"

# ─── Step 3: Copy common templates ──────────────────────────────────────────────
print_step 3 "Copying common templates"

# Create target directories
mkdir -p "$TARGET_DIR/.github/workflows"
mkdir -p "$TARGET_DIR/.github/ISSUE_TEMPLATE"
mkdir -p "$TARGET_DIR/.husky"
mkdir -p "$TARGET_DIR/scripts"

# Copy common config files
copy_file() {
  local src="$1"
  local dest="$2"
  if [ -f "$src" ]; then
    cp "$src" "$dest"
    print_success "$(basename "$dest")"
  fi
}

# Editor & formatting configs
copy_file "$TEMPLATES_DIR/common/.editorconfig" "$TARGET_DIR/.editorconfig"
copy_file "$TEMPLATES_DIR/common/.prettierrc.mjs" "$TARGET_DIR/.prettierrc.mjs"
copy_file "$TEMPLATES_DIR/common/commitlint.config.mjs" "$TARGET_DIR/commitlint.config.mjs"

# Husky hooks
copy_file "$TEMPLATES_DIR/common/.husky/pre-commit" "$TARGET_DIR/.husky/pre-commit"
copy_file "$TEMPLATES_DIR/common/.husky/commit-msg" "$TARGET_DIR/.husky/commit-msg"
chmod +x "$TARGET_DIR/.husky/pre-commit" "$TARGET_DIR/.husky/commit-msg"

# Kebab-case validation script
copy_file "$TEMPLATES_DIR/common/scripts/check-kebab-case.sh" "$TARGET_DIR/scripts/check-kebab-case.sh"
chmod +x "$TARGET_DIR/scripts/check-kebab-case.sh"

# Create-issue CLI script
copy_file "$TEMPLATES_DIR/common/scripts/create-issue.sh" "$TARGET_DIR/scripts/create-issue.sh"
chmod +x "$TARGET_DIR/scripts/create-issue.sh"

# Lint-staged config (framework-specific)
if [ "$FRAMEWORK" = "flutter" ]; then
  copy_file "$TEMPLATES_DIR/flutter/lint-staged.config.mjs" "$TARGET_DIR/lint-staged.config.mjs"
else
  copy_file "$TEMPLATES_DIR/common/lint-staged.config.mjs" "$TARGET_DIR/lint-staged.config.mjs"
fi

# GitHub workflows (common — framework-agnostic)
for workflow in pr-title.yml branch-naming.yml pr-autofill.yml create-branch.yml issue-auto-assign.yml e2e.yml check-devkit-updates.yml; do
  copy_file "$TEMPLATES_DIR/common/.github/workflows/$workflow" "$TARGET_DIR/.github/workflows/$workflow"
done

# GitHub issue templates
for template in bug-report.yml feature-request.yml chore.yml config.yml; do
  copy_file "$TEMPLATES_DIR/common/.github/ISSUE_TEMPLATE/$template" "$TARGET_DIR/.github/ISSUE_TEMPLATE/$template"
done

# Dependabot
copy_file "$TEMPLATES_DIR/common/.github/dependabot.yml" "$TARGET_DIR/.github/dependabot.yml"

# ─── Step 4: Copy framework-specific templates ──────────────────────────────────
print_step 4 "Copying $FRAMEWORK-specific templates"

# CI workflow
copy_file "$TEMPLATES_DIR/$FRAMEWORK/.github/workflows/ci.yml" "$TARGET_DIR/.github/workflows/ci.yml"

# .gitignore
copy_file "$TEMPLATES_DIR/$FRAMEWORK/.gitignore" "$TARGET_DIR/.gitignore"

# Linting config
if [ "$FRAMEWORK" = "flutter" ]; then
  copy_file "$TEMPLATES_DIR/$FRAMEWORK/analysis_options.yaml" "$TARGET_DIR/analysis_options.yaml"
else
  copy_file "$TEMPLATES_DIR/$FRAMEWORK/eslint.config.mjs" "$TARGET_DIR/eslint.config.mjs"
fi

# ─── Step 5: Uncomment Flutter-specific dependabot config ────────────────────────
if [ "$FRAMEWORK" = "flutter" ]; then
  print_step 5 "Enabling Flutter-specific configs"

  # Uncomment the pub ecosystem block in dependabot.yml
  if [ -f "$TARGET_DIR/.github/dependabot.yml" ]; then
    sed -i '' 's/^  # - package-ecosystem: "pub"/  - package-ecosystem: "pub"/' "$TARGET_DIR/.github/dependabot.yml"
    sed -i '' 's/^  #   directory:/    directory:/' "$TARGET_DIR/.github/dependabot.yml"
    sed -i '' 's/^  #   schedule:/    schedule:/' "$TARGET_DIR/.github/dependabot.yml"
    sed -i '' 's/^  #     interval:/      interval:/' "$TARGET_DIR/.github/dependabot.yml"
    sed -i '' 's/^  #     day:/      day:/' "$TARGET_DIR/.github/dependabot.yml"
    sed -i '' 's/^  #   target-branch:/    target-branch:/' "$TARGET_DIR/.github/dependabot.yml"
    sed -i '' 's/^  #   commit-message:/    commit-message:/' "$TARGET_DIR/.github/dependabot.yml"
    sed -i '' 's/^  #     prefix:/      prefix:/' "$TARGET_DIR/.github/dependabot.yml"
    sed -i '' 's/^  #   labels:/    labels:/' "$TARGET_DIR/.github/dependabot.yml"
    sed -i '' 's/^  #     - "dependencies"/      - "dependencies"/' "$TARGET_DIR/.github/dependabot.yml"
    print_success "Enabled pub ecosystem in dependabot.yml"
  fi
else
  print_step 5 "No framework-specific adjustments needed"
fi

# ─── Step 6: Summary ────────────────────────────────────────────────────────────
print_step 6 "Setup complete!"

echo ""
echo -e "${BOLD}${GREEN}═══════════════════════════════════════════════════${NC}"
echo -e "${BOLD}${GREEN}  Setup Complete!${NC}"
echo -e "${BOLD}${GREEN}═══════════════════════════════════════════════════${NC}"
echo ""
echo -e "  ${BOLD}Framework:${NC}     $FRAMEWORK"
echo -e "  ${BOLD}Prefix:${NC}        $PROJECT_PREFIX"
echo -e "  ${BOLD}Repo:${NC}          $GITHUB_REPO"
echo -e "  ${BOLD}Project board:${NC} #$PROJECT_NUMBER"
echo -e "  ${BOLD}Assignee:${NC}      $ASSIGNEE"
echo -e "  ${BOLD}Branches:${NC}      $MAIN_BRANCH / $DEV_BRANCH"
echo ""
echo -e "  ${BOLD}Files created:${NC}"
echo "    .dev-kit.yml"
echo "    .editorconfig"
echo "    .prettierrc.mjs"
echo "    commitlint.config.mjs"
echo "    lint-staged.config.mjs"
echo "    .husky/pre-commit"
echo "    .husky/commit-msg"
echo "    scripts/check-kebab-case.sh"
echo "    scripts/create-issue.sh"
echo "    .github/workflows/ (ci, pr-title, branch-naming, pr-autofill, create-branch, issue-auto-assign)"
echo "    .github/ISSUE_TEMPLATE/ (bug-report, feature-request, chore)"
echo "    .github/dependabot.yml"
echo "    .gitignore"
if [ "$FRAMEWORK" = "flutter" ]; then
  echo "    analysis_options.yaml"
else
  echo "    eslint.config.mjs"
fi
echo ""
echo -e "  ${BOLD}Next steps:${NC}"
echo "    1. Install dev dependencies:"
if [ "$FRAMEWORK" = "flutter" ]; then
  echo "       flutter pub add --dev flutter_lints"
else
  echo "       npm install --save-dev husky lint-staged prettier eslint eslint-config-prettier @commitlint/cli @commitlint/config-conventional"
fi
echo "    2. Add to package.json (JS/TS only):"
echo '       "prepare": "husky"'
echo "    3. Run: npx husky (to initialize hooks)"
echo "    4. Create your first issue:"
echo "       bash scripts/create-issue.sh --type feat --title \"initial setup\""
echo ""
